# Generated by Django 5.0.6 on 2024-05-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('status', models.CharField(choices=[('in_stock', 'Còn hàng'), ('out_of_stock', 'Hết hàng'), ('discontinued', 'Ngừng kinh doanh')], default='in_stock', max_length=20)),
            ],
        ),
    ]
